export const EASY_MOVIES = [
  "Sholay", "DDLJ", "Kabhi Khushi Kabhie Gham", "Kuch Kuch Hota Hai", "Hum Aapke Hain Koun",
  "Raja Hindustani", "Border", "Gadar", "Lagaan", "Swades", "Rang De Basanti", "Chak De India",
  "3 Idiots", "Taare Zameen Par", "Jab We Met", "Om Shanti Om", "Chennai Express", "Golmaal",
  "Hera Pheri", "Andaz Apna Apna", "Mr India", "Qayamat Se Qayamat Tak", "Maine Pyar Kiya",
  "Hum Dil De Chuke Sanam", "Devdas", "Black", "Rab Ne Bana Di Jodi", "Band Baaja Baaraat",
  "Zindagi Na Milegi Dobara", "Yeh Jawaani Hai Deewani", "Barfi", "PK", "Bajrangi Bhaijaan",
  "Dangal", "Secret Superstar", "Sanju", "Tiger Zinda Hai", "Sultan", "Kick", "Bodyguard",
  "Dabangg", "Wanted", "Singham", "Toilet Ek Prem Katha", "Badhaai Ho", "Stree", "Andhadhun",
  "Uri", "Kesari", "Mission Mangal", "Chhichhore", "Dream Girl", "Housefull", "Welcome",
  "Bhool Bhulaiyaa", "Fukrey", "Pyaar Ka Punchnama", "Judwaa", "Coolie No. 1", "Aankhen",
  "Hungama", "All The Best", "Ready", "Desi Boyz", "Namastey London", "Partner", "Singh Is Kinng",
  "Sonu Ke Titu Ki Sweety", "Badlapur", "Tanu Weds Manu", "Raanjhanaa", "Queen", "Haider", "Pink",
  "Newton", "Hindi Medium", "October", "Tumhari Sulu", "Shubh Mangal Saavdhan", "Piku",
  "Bajirao Mastani", "Drishyam", "Padmaavat", "Raabta", "Veere Di Wedding", "A Gentleman",
  "Dishoom", "Sanam Teri Kasam", "Flying Jatt", "Hasee Toh Phasee", "Rockstar", "Wake Up Sid",
  "Love Aaj Kal", "My Name Is Khan", "Udaan", "Kites", "Fashion", "Blue", "Tevar", "Baby",
  "Jawan", "Pathaan", "Animal", "Gully Boy", "War", "Simmba", "Sooryavanshi", "Brahmastra",
  "Bhool Bhulaiyaa 2", "Gangubai Kathiawadi", "Jug Jugg Jeeyo", "Laapataa Ladies", "Fighter",
  "Dunki", "Shaitaan", "Crew", "Bade Miyan Chote Miyan", "Maidaan", "Srikanth", "Mr & Mrs Mahi",
  "Chandu Champion", "Mother India", "Mughal-e-Azam", "Guide", "Pyaasa", "Kabhi Kabhie",
  "Amar Akbar Anthony", "Don", "Deewaar", "Trishul", "Kranti", "Mr Natwarlal", "Naseeb", "Coolie",
  "Mard", "Tezaab", "Ram Lakhan", "Chandni", "Henna", "Dil", "Hum", "Jo Jeeta Wohi Sikandar",
  "Khiladi", "Baazigar", "Darr", "Anjaam", "Dilwale", "Yes Boss", "Pyaar Kiya To Darna Kya",
  "Pyaar To Hona Hi Tha", "Kaho Naa Pyaar Hai", "Mohabbatein", "Veer Zaara", "Bunty Aur Babli",
  "Salaam Namaste", "Parineeta", "Kabhi Alvida Naa Kehna", "Don 2", "Jab Tak Hai Jaan", "Dhoom",
  "Dhoom 2", "Dhoom 3", "Bang Bang", "Krrish", "Krrish 3", "Ra.One", "Happy New Year", "Fan",
  "Dear Zindagi", "Pad Man", "Ram Setu", "Housefull 4", "Prem Ratan Dhan Payo", "Bharat",
  "Golmaal 3", "Golmaal Returns", "Welcome Back", "Total Dhamaal", "Double Dhamaal",
  "Phir Hera Pheri", "Life Partner", "All Is Well", "Holiday", "Kyaa Super Kool Hain Hum",
  "Grand Masti", "Atithi Tum Kab Jaoge", "Thank You", "Khatta Meetha", "Singh Saab The Great",
  "Jolly LLB 2", "Rowdy Rathore", "Son of Sardaar", "Gabbar Is Back", "Brothers",
  "Tanu Weds Manu Returns", "Nil Battey Sannata", "Bareilly Ki Barfi", "Shubh Mangal Zyada Saavdhan"
];

export const HARD_MOVIES = [
  "Matru Ki Bijlee Ka Mandola", "Andheri Raat Mein Diya Tere Haath Mein", "Allah Meherban Toh Gadhha Pehelwan",
  "Aamdani Athanni Kharcha Rupaiya", "Shin Shinaki Boobla Boo", "Bhoot Bungla", "Ladoo Singh Taxiwala",
  "Jadugar Daku", "Aaj Ka Robin Hood", "Rakhi Aur Rifle", "Haseena Haathi Waali", "Paap Ki Duniya",
  "Be Dhari Talwar", "The Light of the World", "Inspector", "Fashionable India", "Inquilab",
  "Romantic India", "Qazzak Ki Ladki", "Kamaal Dhamaal Malamaal", "Ata Pata Lapatta", "Super Dhamaal.com",
  "Life Ki Toh Lag Gayi", "In the Name of Tai", "Be-Careful", "Dus Tola", "Mastang", "Bheja Fry 2",
  "Mere Baap Pehle Aap", "Ek Chalis Ki Last Local", "Khuda Gawah", "Oye Lucky Lucky Oye",
  "Saare Jahaan Se Accha", "Ek Ladki Ko Dekha Toh Aisa Laga", "Khosla Ka Ghosla", "Ram Gopal Varma Ki Aag",
  "Guddi", "Hulla", "Mohenjo Daro", "Itefaq", "Guzaarish", "Anamika", "Kabir Singh", "Zabardast",
  "Stone Man Murders", "Sangharsh", "Kartavya", "Mukhbir", "Shirin Farhad Ki Toh Nikal Padi",
  "Akhiyon Ke Jharokhon Se", "Chaalbaaz", "Lootera", "Madras Cafe", "Shahid", "Bhaag Milkha Bhaag",
  "Ship of Theseus", "The Lunchbox", "Margarita With A Straw", "Dum Laga Ke Haisha", "Masaan",
  "Talvar", "Dedh Ishqiya", "Mukti Bhawan", "Anaarkali of Aarah", "Kaabil", "Raees", "Tubelight",
  "Jagga Jasoos", "Indu Sarkar", "Gunjan Saxena", "Ludo", "Shakuntala Devi", "Mimi", "Sherni",
  "Toofaan", "Sardar Udham", "Chandigarh Kare Aashiqui", "Shershaah", "Gehraiyaan", "Badhaai Do",
  "Runway 34", "Uunchai", "Drishyam 2", "Bhediya", "Goodbye", "Cirkus", "Tu Jhoothi Main Makkaar",
  "Nanu Ki Jaanu", "Trapped", "A Death in the Gunj", "Poorna", "Ventilator", "The Blue Umbrella",
  "Is Love Enough Sir", "Dhobi Ghat", "Dil Se..", "Zubeidaa", "Socha Na Tha", "Court", "Peepli Live",
  "Ugly", "That Girl in Yellow Boots", "No One Killed Jessica", "Iqbal", "Page 3", "Haasil",
  "Albert Pinto Ko Gussa Kyoon Aata Hai", "Do Bigha Zameen", "Kaagaz Ke Phool", "Sahib Bibi Aur Ghulam",
  "Teesri Manzil", "Aradhana", "Anand", "Jaane Bhi Do Yaaro", "Chupke Chupke", "Gol Maal", "Angoor",
  "Masoom", "Sparsh", "Arth", "Saaransh", "Parinda", "Salim Langde Pe Mat Ro", "Mira", "Percy", "Sur",
  "Rudaali", "Bandit Queen", "Sardari Begum", "Mrityudand", "Hazaar Chaurasi Ki Maa", "Godmother",
  "Shool", "Aks", "Jism", "Pinjar", "Tehzeeb", "15 Park Avenue", "Kabul Express", "Black Friday",
  "Paanch", "Dev D", "Manorama Six Feet Under", "Johnny Gaddaar", "A Wednesday", "Mumbai Meri Jaan",
  "Oye Lucky!", "Agyaat", "Road, Movie", "Well Done Abba", "Do Dooni Chaar", "Antaheen", "Gandu",
  "I Am", "Kshay", "The Disciple", "Eeb Allay Ooo!", "Axone", "Bulbbul", "AK vs AK", "Serious Men",
  "Tribhanga", "The White Tiger", "Pagglait", "Sandeep Aur Pinky Faraar", "A Thursday", "Maja Ma",
  "Dasvi", "Jhund", "Qala", "Monica O My Darling", "Afwaah", "Bawaal", "Mrs Undercover", "Jaane Jaan",
  "12th Fail", "Apurva", "Sector 36", "Stolen", "Aankhon Ki Gustakhiyaan", "Ghoomketu", "Gulabo Sitabo",
  "Gunjan Saxena: The Kargil Girl", "Karwaan", "Kaanchli", "Lipstick Under My Burkha", "Mulk", "Pari",
  "Photograph", "Rasbhari", "Thappad"
];
